# Generated by Django 4.1.3 on 2022-12-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nutritionist_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('ssn', models.TextField(max_length=30, unique=True)),
            ],
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='MemberTiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(max_length=1, unique=True)),
                ('monthlyFee', models.FloatField(unique=True)),
            ],
        ),
    ]
