# Generated by Django 4.1.3 on 2022-12-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_member_membertiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertiers',
            name='monthlyFee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='membertiers',
            name='tier',
            field=models.IntegerField(unique=True),
        ),
    ]
