# Generated by Django 4.1.3 on 2022-12-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_membertiers_monthlyfee_alter_membertiers_tier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberTiers',
            new_name='Tier',
        ),
    ]
