# Generated by Django 4.1.3 on 2022-12-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_membertiers_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='desc',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
