# Generated by Django 4.1.3 on 2022-12-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_member_salary_nutritionist_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='salary',
        ),
        migrations.AddField(
            model_name='trainer',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
